---
toc: true
layout: post
description: "Explanation of the paper: mixup: Beyond Empirical Risk Minimization"
categories: [paper summary]
title: "mixup: Beyond Empirical Risk Minimization"
comments: true
---

# mixup: Beyond Empirical Risk Minimization

If you participate in Kaggle competitions especially related to image classification, you must have definately seen a notebook implementing Mixup probably along with cross validation or any other augmentation method such as CutMix, GridMask, etc which makes this a pretty important concept to have in your toolbox. During my undergraduate thesis when I was working with thermal images, I suspected that my network might suffering due to the presence of corrupted labels in the dataset. Although I had no proof about the presence of such images, I wanted to find something which makes my network more robust and generalizable. This is when I came across [Mixup](https://arxiv.org/abs/1710.09412)

Mixup is a data augmentation method which comes with a promise to make neural networks more **generalizable**, **reduces memorization of corrupted labels**, **increases robustness** and **stabalizes training of Generative Adversarial Networks (GANs)**. It does so by training the network on combinations of examples in the datasets (images) and their labels. 

## Motivation

A common observed practice in deep learning is that the size of the neural networks increases with increase in size of the dataset with the best example being GPT-3. If you do not know about GPT-3, you are either living under a rock or you are not (active) on Twitter. Basically, GPT-3 is a language model by Open AI which was trained on (almost) the entire web. This model is so huge that it takes 300 GB of space just to store the weights of this model. Now that we have an idea about the size of current models and datasets, lets talk about an interesting result from the classical learning theory which which laid the foundation of modern Machine Learning. This result states that **Convergence of Empirical Risk Minimization (ERM) is guaranteed if the size of Neural Networks does not increase with the size in data.** (ERM is the learning rule which minimizes the average error of deep models during training which is essentialy how we currently train our networks.) This rule is in direct contradiction of how we currently train our models which also challenges the efficacy of ERM.

Memorization tendencies of neural networks are very well covered in the seminal paper [Understanding deep learning requires rethinking generalization](https://arxiv.org/abs/1611.03530). Along with this, neural networks have also been accused of behaving very differently in presence of adverserial examples. This observations motivated the authors to look at methods beyond ERM. 

## Methodology

The authors introduce mixup as a data-agnostic augmentation routine which helps networks generalize better. The equation of mixup is defined below: 

![]({{ site.baseurl }}/images/Mixup/equation.PNG "Mixup Equation to create new training samples")

Here, 
1. x' and y' is the new training sample/ label generated by augmentation
2. x(i) and x(j) are raw input vectors (images)
3. y(i) and y(j) are one-hot encoded labels
4. Lambda is the mixup parameter which (in a sense) controls the amount of augmentation

